# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

"""
Tests for control flow code generation (scf.for and scf.if) using PyPTO frontend.

This module validates that scf.for and scf.if are correctly generated by the PTO codegen,
ensuring correct code generation and execution for loop and conditional patterns.

Test Coverage:
    - For loops with tile operations (add, mul) ✅
    - If-else with scalar boolean conditions inside InCore functions ✅
    - Both CCE and PTO backend variants ✅
    - For+if-else nested pattern (marked as XFAIL due to known issue) ⚠️

Key Requirements for If-Else in InCore Functions:
    - Use pl.Scalar[pl.BOOL] for condition parameters (not INT64)
    - Both branches must use the SAME variable names for assignments
    - Avoid if-else inside for loops due to variable scoping issues (see XFAIL tests)
    - Pattern based on kernel_online_update from paged_attention_example.py

Known Issue - For Loop with Nested If-Else:
    When if-else is nested inside a for loop, the SSA transformation creates different
    variable names for each iteration (out_0, out_1, out_2, ...) in different branches.
    After the loop completes, the return statement cannot determine which variable to use.

    Example of the problem:
        for i in range(4):
            if condition:
                out: Tensor = store(...)  # Becomes out_0, out_1, out_2, out_3
            else:
                out: Tensor = store(...)  # Becomes out_0, out_1, out_2, out_3
        return out  # Which out? out_0 or out_3?

    Workaround: Place if-else outside the for loop, or use separate kernels for each branch.
    See TestForIfElseNestedXFAIL for a minimal reproduction case.
"""

from typing import Any

import pypto.language as pl
import pytest
from harness.core.harness import DataType, PTOTestCase, TensorSpec
from pypto.backend import BackendType
from pypto.ir.pass_manager import OptimizationStrategy


class TestForLoopAdd(PTOTestCase):
    """Test tile add inside a for loop (1 iteration).

    Validates scf.for code generation. The loop runs once,
    performing a simple tile add. Expected result: c = a + b.
    """

    __test__ = False

    def get_name(self) -> str:
        return "for_loop_add_64x64"

    def define_tensors(self) -> list[TensorSpec]:
        return [
            TensorSpec("a", [256, 64], DataType.FP32, init_value=2.0),
            TensorSpec("b", [256, 64], DataType.FP32, init_value=3.0),
            TensorSpec("c", [256, 64], DataType.FP32, is_output=True),
        ]

    def get_program(self) -> Any:
        @pl.program
        class ForLoopAddProgram:
            @pl.function(type=pl.FunctionType.InCore)
            def kernel_add_loop(
                self,
                a: pl.Tensor[[256, 64], pl.FP32],
                b: pl.Tensor[[256, 64], pl.FP32],
                c: pl.Out[pl.Tensor[[256, 64], pl.FP32]],
            ) -> pl.Tensor[[256, 64], pl.FP32]:
                for i in pl.range(4):
                    offset_i = i * 64
                    tile_a: pl.Tile[[64, 64], pl.FP32] = pl.load(a, [offset_i, 0], [64, 64])
                    tile_b: pl.Tile[[64, 64], pl.FP32] = pl.load(b, [offset_i, 0], [64, 64])
                    tile_c: pl.Tile[[64, 64], pl.FP32] = pl.add(tile_a, tile_b)
                    out: pl.Tensor[[256, 64], pl.FP32] = pl.store(tile_c, [offset_i, 0], [64, 64], c)
                return out

            @pl.function(type=pl.FunctionType.Orchestration)
            def orchestrator(
                self,
                a: pl.Tensor[[256, 64], pl.FP32],
                b: pl.Tensor[[256, 64], pl.FP32],
            ) -> pl.Tensor[[256, 64], pl.FP32]:
                c: pl.Tensor[[256, 64], pl.FP32] = pl.create_tensor([256, 64], dtype=pl.FP32)
                c = self.kernel_add_loop(a, b, c)
                return c

        return ForLoopAddProgram

    def compute_expected(self, tensors, params=None):
        tensors["c"][:] = tensors["a"] + tensors["b"]


class TestForLoopAddPTO(TestForLoopAdd):
    """Test for loop add with PTO backend and PTOAS optimization."""

    __test__ = False

    def get_name(self) -> str:
        return "for_loop_add_pto_64x64"

    def get_strategy(self) -> OptimizationStrategy:
        return OptimizationStrategy.PTOAS

    def get_backend_type(self) -> BackendType:
        return BackendType.PTO


class TestForLoopMul(PTOTestCase):
    """Test tile mul inside a for loop (1 iteration).

    Validates scf.for code generation with a different operation.
    Expected result: c = a * b.
    """

    __test__ = False

    def get_name(self) -> str:
        return "for_loop_mul_64x64"

    def define_tensors(self) -> list[TensorSpec]:
        return [
            TensorSpec("a", [256, 64], DataType.FP32, init_value=2.0),
            TensorSpec("b", [256, 64], DataType.FP32, init_value=3.0),
            TensorSpec("c", [256, 64], DataType.FP32, is_output=True),
        ]

    def get_program(self) -> Any:
        @pl.program
        class ForLoopMulProgram:
            @pl.function(type=pl.FunctionType.InCore)
            def kernel_mul_loop(
                self,
                a: pl.Tensor[[256, 64], pl.FP32],
                b: pl.Tensor[[256, 64], pl.FP32],
                c: pl.Out[pl.Tensor[[256, 64], pl.FP32]],
            ) -> pl.Tensor[[256, 64], pl.FP32]:
                for i in pl.range(4):
                    offset_i = i * 64
                    tile_a: pl.Tile[[64, 64], pl.FP32] = pl.load(a, [offset_i, 0], [64, 64])
                    tile_b: pl.Tile[[64, 64], pl.FP32] = pl.load(b, [offset_i, 0], [64, 64])
                    tile_c: pl.Tile[[64, 64], pl.FP32] = pl.mul(tile_a, tile_b)
                    out: pl.Tensor[[256, 64], pl.FP32] = pl.store(tile_c, [offset_i, 0], [64, 64], c)
                return out

            @pl.function(type=pl.FunctionType.Orchestration)
            def orchestrator(
                self,
                a: pl.Tensor[[256, 64], pl.FP32],
                b: pl.Tensor[[256, 64], pl.FP32],
            ) -> pl.Tensor[[256, 64], pl.FP32]:
                c: pl.Tensor[[256, 64], pl.FP32] = pl.create_tensor([256, 64], dtype=pl.FP32)
                c = self.kernel_mul_loop(a, b, c)
                return c

        return ForLoopMulProgram

    def compute_expected(self, tensors, params=None):
        tensors["c"][:] = tensors["a"] * tensors["b"]


class TestForLoopMulPTO(TestForLoopMul):
    """Test for loop mul with PTO backend and PTOAS optimization."""

    __test__ = False

    def get_name(self) -> str:
        return "for_loop_mul_pto_64x64"

    def get_strategy(self) -> OptimizationStrategy:
        return OptimizationStrategy.PTOAS

    def get_backend_type(self) -> BackendType:
        return BackendType.PTO


class TestIfElseInCore(PTOTestCase):
    """Test if-else inside InCore function with scalar condition.

    Based on the pattern from kernel_online_update in paged_attention_example.py.
    Key: both branches must assign to the same output variables.
    """

    __test__ = False

    def get_name(self) -> str:
        return "if_else_incore"

    def define_tensors(self) -> list[TensorSpec]:
        return [
            TensorSpec("a", [64, 64], DataType.FP32, init_value=2.0),
            TensorSpec("b", [64, 64], DataType.FP32, init_value=3.0),
            TensorSpec("c", [64, 64], DataType.FP32, is_output=True),
        ]

    def get_program(self) -> Any:
        @pl.program
        class IfElseInCoreProgram:
            @pl.function(type=pl.FunctionType.InCore)
            def kernel_conditional(
                self,
                a: pl.Tensor[[64, 64], pl.FP32],
                b: pl.Tensor[[64, 64], pl.FP32],
                c: pl.Out[pl.Tensor[[64, 64], pl.FP32]],
                use_add: pl.Scalar[pl.BOOL],
            ) -> pl.Tensor[[64, 64], pl.FP32]:
                tile_a: pl.Tile[[64, 64], pl.FP32] = pl.load(a, [0, 0], [64, 64])
                tile_b: pl.Tile[[64, 64], pl.FP32] = pl.load(b, [0, 0], [64, 64])

                # Both branches must use the SAME variable names
                if use_add:
                    tile_result: pl.Tile[[64, 64], pl.FP32] = pl.add(tile_a, tile_b)
                    out: pl.Tensor[[64, 64], pl.FP32] = pl.store(tile_result, [0, 0], [64, 64], c)
                else:
                    tile_result: pl.Tile[[64, 64], pl.FP32] = pl.sub(tile_a, tile_b)
                    out: pl.Tensor[[64, 64], pl.FP32] = pl.store(tile_result, [0, 0], [64, 64], c)

                return out

            @pl.function(type=pl.FunctionType.Orchestration)
            def orchestrator(
                self,
                a: pl.Tensor[[64, 64], pl.FP32],
                b: pl.Tensor[[64, 64], pl.FP32],
            ) -> pl.Tensor[[64, 64], pl.FP32]:
                c: pl.Tensor[[64, 64], pl.FP32] = pl.create_tensor([64, 64], dtype=pl.FP32)
                use_add = True  # Use add operation
                c = self.kernel_conditional(a, b, c, use_add)
                return c

        return IfElseInCoreProgram

    def compute_expected(self, tensors, params=None):
        # use_add = 1, so we do addition
        tensors["c"][:] = tensors["a"] + tensors["b"]


class TestIfElseInCorePTO(TestIfElseInCore):
    """Test if-else InCore with PTO backend and PTOAS optimization."""

    __test__ = False

    def get_name(self) -> str:
        return "if_else_incore_pto"

    def get_strategy(self) -> OptimizationStrategy:
        return OptimizationStrategy.PTOAS

    def get_backend_type(self) -> BackendType:
        return BackendType.PTO


class TestForIfElseNested(PTOTestCase):
    """Test for loop with if-else nested inside.

    This test demonstrates the variable scoping issue when if-else is nested
    inside a for loop. The problem: each loop iteration creates new variable
    names (out_0, out_1, out_2...) in different branches, and the return
    statement cannot find the correct variable after the loop.

    Issue: Variable scoping in for loops with if-else branches.
    """

    __test__ = False

    def get_name(self) -> str:
        return "for_if_else_nested"

    def define_tensors(self) -> list[TensorSpec]:
        return [
            TensorSpec("a", [256, 64], DataType.FP32, init_value=2.0),
            TensorSpec("b", [256, 64], DataType.FP32, init_value=3.0),
            TensorSpec("c", [256, 64], DataType.FP32, is_output=True),
        ]

    def get_program(self) -> Any:
        @pl.program
        class ForIfElseNestedProgram:
            @pl.function(type=pl.FunctionType.InCore)
            def kernel_loop_with_if(
                self,
                a: pl.Tensor[[256, 64], pl.FP32],
                b: pl.Tensor[[256, 64], pl.FP32],
                c: pl.Out[pl.Tensor[[256, 64], pl.FP32]],
                use_add: pl.Scalar[pl.BOOL],
            ) -> pl.Tensor[[256, 64], pl.FP32]:
                # If-else INSIDE the for loop - this causes variable scoping issues
                for i in pl.range(4):
                    offset_i = i * 64
                    tile_a: pl.Tile[[64, 64], pl.FP32] = pl.load(a, [offset_i, 0], [64, 64])
                    tile_b: pl.Tile[[64, 64], pl.FP32] = pl.load(b, [offset_i, 0], [64, 64])

                    # Problem: Each iteration creates out_0, out_1, out_2, out_3
                    # in different branches, causing variable scoping issues
                    if use_add:
                        tile_result: pl.Tile[[64, 64], pl.FP32] = pl.add(tile_a, tile_b)
                        out: pl.Tensor[[256, 64], pl.FP32] = pl.store(tile_result, [offset_i, 0], [64, 64], c)
                    else:
                        tile_result: pl.Tile[[64, 64], pl.FP32] = pl.mul(tile_a, tile_b)
                        out: pl.Tensor[[256, 64], pl.FP32] = pl.store(tile_result, [offset_i, 0], [64, 64], c)

                # After loop: which 'out' to return? out_0 from iteration 0? out_3 from iteration 3?
                return out

            @pl.function(type=pl.FunctionType.Orchestration)
            def orchestrator(
                self,
                a: pl.Tensor[[256, 64], pl.FP32],
                b: pl.Tensor[[256, 64], pl.FP32],
            ) -> pl.Tensor[[256, 64], pl.FP32]:
                c: pl.Tensor[[256, 64], pl.FP32] = pl.create_tensor([256, 64], dtype=pl.FP32)
                use_add = False
                c = self.kernel_loop_with_if(a, b, c, use_add)
                return c

        return ForIfElseNestedProgram

    def compute_expected(self, tensors, params=None):
        tensors["c"][:] = tensors["a"] * tensors["b"]


class TestForIfElseNestedPTO(TestForIfElseNested):
    """Test for+if-else nested with PTO backend - EXPECTED TO FAIL."""

    __test__ = False

    def get_name(self) -> str:
        return "for_if_else_nested_xfail_pto"

    def get_strategy(self) -> OptimizationStrategy:
        return OptimizationStrategy.PTOAS

    def get_backend_type(self) -> BackendType:
        return BackendType.PTO


# =============================================================================
# pytest test functions
# =============================================================================


class TestCtrlFlowOperations:
    """Test suite for control flow operations."""

    def test_for_loop_add(self, test_runner):
        """Test for loop wrapping tile add."""
        test_case = TestForLoopAdd()
        result = test_runner.run(test_case)
        assert result.passed, f"Test failed: {result.error}"

    def test_for_loop_add_pto(self, test_runner):
        """Test for loop add with PTO backend and PTOAS."""
        test_case = TestForLoopAddPTO()
        result = test_runner.run(test_case)
        assert result.passed, f"Test failed (PTO): {result.error}"

    def test_for_loop_mul(self, test_runner):
        """Test for loop wrapping tile mul."""
        test_case = TestForLoopMul()
        result = test_runner.run(test_case)
        assert result.passed, f"Test failed: {result.error}"

    def test_for_loop_mul_pto(self, test_runner):
        """Test for loop mul with PTO backend and PTOAS."""
        test_case = TestForLoopMulPTO()
        result = test_runner.run(test_case)
        assert result.passed, f"Test failed (PTO): {result.error}"

    def test_if_else_incore(self, test_runner):
        """Test if-else inside InCore function."""
        test_case = TestIfElseInCore()
        result = test_runner.run(test_case)
        assert result.passed, f"Test failed: {result.error}"

    def test_if_else_incore_pto(self, test_runner):
        """Test if-else InCore with PTO backend and PTOAS."""
        test_case = TestIfElseInCorePTO()
        result = test_runner.run(test_case)
        assert result.passed, f"Test failed (PTO): {result.error}"

    @pytest.mark.xfail(
        reason="Variable scoping issue: if-else inside for loop creates different variable names "
        "in each iteration (out_0, out_1, ...), causing 'Variable not found' error after loop. "
        "See TestForIfElseNestedXFAIL docstring for details.",
        strict=True,
    )
    def test_for_if_else_nested(self, test_runner):
        """Test for loop with if-else nested inside - EXPECTED TO FAIL."""
        test_case = TestForIfElseNested()
        result = test_runner.run(test_case)
        assert result.passed, f"Test failed: {result.error}"

    @pytest.mark.xfail(
        reason="Variable scoping issue with PTO backend: if-else inside for loop. "
        "Same issue as CCE backend plus potential MLIR type mismatches.",
        strict=True,
    )
    def test_for_if_else_nested_pto(self, test_runner):
        """Test for+if-else nested with PTO backend - EXPECTED TO FAIL."""
        test_case = TestForIfElseNestedPTO()
        result = test_runner.run(test_case)
        assert result.passed, f"Test failed (PTO): {result.error}"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
