# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

"""Shared discovery of the ``ptoas`` executable under ``$PTOAS_ROOT``."""

import os
import shutil
import sys

# Probed in order under $PTOAS_ROOT — the release layout changed twice, and the
# three entries are NOT interchangeable:
#
# - up to v0.50, `<root>/ptoas` is a shell launcher that exports
#   `LD_LIBRARY_PATH=<root>/lib` before exec'ing `<root>/bin/ptoas`. That bare
#   binary has no RUNPATH, so invoking it directly dies with
#   "libMLIR*.so: cannot open shared object file". The launcher must win.
# - the wheel layout (what CI installs) makes `<root>` a venv: only
#   `<root>/bin/ptoas` exists, a console script whose shebang names that venv's
#   own interpreter, so it is self-sufficient and the probe falls through to it.
# - the v0.55+ standalone archive has `<root>/ptoas` as a Python package
#   *directory* (not executable) and `<root>/bin/ptoas` as a plain
#   `#!/usr/bin/env python3` wrapper. That wrapper is NOT self-sufficient: the
#   archive pins an interpreter in `<root>/.ptoas-python-version` (3.11 as of
#   v0.57) and its native libraries live in `<root>/lib`. `<root>/ptoas.sh` is
#   the launcher supplying both — it execs the bundled CPython with
#   `LD_LIBRARY_PATH` set. Reaching `bin/ptoas` instead fails with "this ptoas
#   compiler archive requires CPython 3.11, but the active interpreter is 3.10".
#
# Hence launchers first and the bare wrapper last: correct on all three layouts,
# whereas `bin/ptoas`-first silently breaks both the pre-v0.51 toolchains and
# the v0.55+ archives.
PTOAS_RELATIVE_PATHS = ("ptoas", "ptoas.sh", "bin/ptoas")

# Written at `<root>/.ptoas-python-version` by the v0.55+ standalone archive;
# `<root>/bin/ptoas` refuses to run under any other CPython minor version.
PTOAS_PYTHON_REQUIREMENT_FILE = ".ptoas-python-version"


def find_ptoas_binary() -> str | None:
    """Locate the ``ptoas`` executable.

    When ``PTOAS_ROOT`` is set only that directory is searched — falling back to
    ``PATH`` would silently compile with a different PTOAS than the pinned one.

    Returns:
        Path to the executable, or ``None`` when no executable ``ptoas`` exists.
    """
    ptoas_root = os.environ.get("PTOAS_ROOT")
    if not ptoas_root:
        return shutil.which("ptoas")

    for relative in PTOAS_RELATIVE_PATHS:
        candidate = os.path.join(ptoas_root, relative)
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate
    return None


def describe_python_requirement_mismatch(ptoas_bin: str) -> str | None:
    """Explain a CPython mismatch when *ptoas_bin* is a bare archive wrapper.

    The v0.55+ standalone archive normally ships a ``ptoas.sh`` launcher that
    execs a bundled interpreter, and :func:`find_ptoas_binary` prefers it. But
    that launcher is generated by the PTOAS installer rather than packed into
    the archive, so a hand-extracted tree exposes only the
    ``#!/usr/bin/env python3`` wrapper at ``<root>/bin/ptoas`` — which aborts
    under any interpreter but the pinned one. Turn that bare abort into an
    actionable message.

    Args:
        ptoas_bin: The executable :func:`find_ptoas_binary` resolved. A launcher
            resolves no requirement file and is therefore reported as matching.

    Returns:
        A multi-line explanation, or ``None`` when *ptoas_bin* pins no
        interpreter or pins the one already running.
    """
    root = os.path.dirname(os.path.dirname(os.path.abspath(ptoas_bin)))
    try:
        with open(os.path.join(root, PTOAS_PYTHON_REQUIREMENT_FILE), encoding="utf-8") as handle:
            required = handle.read().strip()
    except OSError:
        return None

    actual = f"{sys.version_info.major}.{sys.version_info.minor}"
    if not required or required == actual:
        return None

    return (
        f"  PyPTO runs on CPython {actual}, but the PTOAS archive at '{root}' pins CPython "
        f"{required} (see {PTOAS_PYTHON_REQUIREMENT_FILE}), and that tree has no executable "
        "'ptoas.sh' launcher to switch interpreters with.\n"
        "  Fix: reinstall this PTOAS through its installer, which generates the launcher, or "
        f"point PTOAS_ROOT at a PTOAS built for CPython {actual}."
    )
